CREATE TABLE IF NOT EXISTS receipt_issuance_attempts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  intake_id BIGINT UNSIGNED NULL,
  normalized_booking_id BIGINT UNSIGNED NULL,
  source VARCHAR(50) NOT NULL DEFAULT 'bolt_mail',
  provider VARCHAR(50) NOT NULL DEFAULT 'aade_mydata',
  environment VARCHAR(30) NOT NULL DEFAULT 'test',
  receipt_mode VARCHAR(40) NOT NULL DEFAULT 'aade_mydata',
  provider_status ENUM('not_attempted','connectivity_ok','connectivity_failed','prepared','issued','failed','skipped') NOT NULL DEFAULT 'not_attempted',
  issuer_vat_number VARCHAR(20) NULL,
  document_type VARCHAR(40) NULL,
  total_amount DECIMAL(10,2) NULL,
  net_amount DECIMAL(10,2) NULL,
  vat_amount DECIMAL(10,2) NULL,
  vat_rate DECIMAL(5,2) NULL,
  http_status INT NULL,
  mark VARCHAR(80) NULL,
  uid VARCHAR(191) NULL,
  qr_url TEXT NULL,
  official_pdf_path TEXT NULL,
  request_payload_hash CHAR(64) NULL,
  request_payload_json LONGTEXT NULL,
  response_payload_json LONGTEXT NULL,
  error_code VARCHAR(100) NULL,
  error_message TEXT NULL,
  created_by VARCHAR(100) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_receipt_intake_id (intake_id),
  KEY idx_receipt_booking_id (normalized_booking_id),
  KEY idx_receipt_provider_status (provider, provider_status),
  KEY idx_receipt_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
