<?php
/**
 * gov.cabnet.app — Safe Handoff Package Archive
 *
 * Admin-only private package browser/downloader for ZIPs generated by:
 * /home/cabnet/gov.cabnet.app_app/cli/build_safe_handoff_package.php
 *
 * Safety:
 * - Does not build ZIPs.
 * - Does not dump the database.
 * - Does not read/display secrets.
 * - Downloads only whitelisted generated handoff ZIP filenames from the private app var folder.
 */

declare(strict_types=1);

header('Content-Type: text/html; charset=utf-8');
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('X-Robots-Tag: noindex,nofollow', true);

if (session_status() !== PHP_SESSION_ACTIVE) {
    session_start();
}

require_once __DIR__ . '/_shell.php';

function hpa_csrf_token(): string
{
    if (empty($_SESSION['handoff_package_archive_csrf']) || !is_string($_SESSION['handoff_package_archive_csrf'])) {
        $_SESSION['handoff_package_archive_csrf'] = bin2hex(random_bytes(32));
    }
    return $_SESSION['handoff_package_archive_csrf'];
}

function hpa_validate_csrf(string $token): bool
{
    return isset($_SESSION['handoff_package_archive_csrf'])
        && is_string($_SESSION['handoff_package_archive_csrf'])
        && hash_equals($_SESSION['handoff_package_archive_csrf'], $token);
}

function hpa_package_dir(): string
{
    return dirname(__DIR__, 3) . '/gov.cabnet.app_app/var/handoff-packages';
}

function hpa_valid_package_name(string $name): bool
{
    return (bool)preg_match('/^gov_cabnet_safe_handoff_\d{8}_\d{6}_(with_db|no_db)\.zip$/', $name);
}

function hpa_safe_path(string $name): string
{
    if (!hpa_valid_package_name($name)) {
        throw new RuntimeException('Invalid package filename.');
    }

    $dir = hpa_package_dir();
    $path = $dir . DIRECTORY_SEPARATOR . $name;
    $realDir = realpath($dir);
    $realPath = realpath($path);

    if ($realDir === false || $realPath === false || !is_file($realPath)) {
        throw new RuntimeException('Package file was not found.');
    }

    $realDir = rtrim(str_replace('\\', '/', $realDir), '/') . '/';
    $realPathNorm = str_replace('\\', '/', $realPath);

    if (!str_starts_with($realPathNorm, $realDir)) {
        throw new RuntimeException('Package path failed safety check.');
    }

    return $realPath;
}

/**
 * @return array<int,array<string,mixed>>
 */
function hpa_list_packages(): array
{
    $dir = hpa_package_dir();
    if (!is_dir($dir)) {
        return [];
    }

    $items = @scandir($dir);
    if (!is_array($items)) {
        return [];
    }

    $out = [];
    foreach ($items as $item) {
        if ($item === '.' || $item === '..' || !hpa_valid_package_name($item)) {
            continue;
        }

        $path = $dir . DIRECTORY_SEPARATOR . $item;
        if (!is_file($path) || !is_readable($path)) {
            continue;
        }

        $size = filesize($path);
        $mtime = filemtime($path);
        $out[] = [
            'name' => $item,
            'path' => $path,
            'size' => $size !== false ? (int)$size : 0,
            'mtime' => $mtime !== false ? (int)$mtime : 0,
            'with_db' => str_contains($item, '_with_db.zip'),
        ];
    }

    usort($out, static function (array $a, array $b): int {
        return ((int)($b['mtime'] ?? 0)) <=> ((int)($a['mtime'] ?? 0));
    });

    return $out;
}

function hpa_bytes(int $bytes): string
{
    if ($bytes < 1024) {
        return $bytes . ' B';
    }
    $units = ['KB', 'MB', 'GB'];
    $value = (float)$bytes;
    foreach ($units as $unit) {
        $value /= 1024;
        if ($value < 1024 || $unit === 'GB') {
            return number_format($value, $unit === 'KB' ? 1 : 2) . ' ' . $unit;
        }
    }
    return number_format($value, 2) . ' GB';
}

function hpa_stream_download(string $fileName): void
{
    $path = hpa_safe_path($fileName);
    $size = filesize($path);
    if ($size === false) {
        throw new RuntimeException('Unable to read package size.');
    }

    while (ob_get_level() > 0) {
        @ob_end_clean();
    }

    header_remove('Content-Type');
    header('Content-Type: application/zip');
    header('Content-Disposition: attachment; filename="' . basename($fileName) . '"');
    header('Content-Length: ' . (string)$size);
    header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
    header('Pragma: no-cache');

    $fh = fopen($path, 'rb');
    if (!$fh) {
        throw new RuntimeException('Unable to open package for download.');
    }

    try {
        while (!feof($fh)) {
            $chunk = fread($fh, 1024 * 1024);
            if ($chunk === false) {
                break;
            }
            echo $chunk;
            flush();
        }
    } finally {
        fclose($fh);
    }
}

$notice = '';
$error = '';

if (!opsui_is_admin()) {
    http_response_code(403);
    echo 'Forbidden. Admin role required.';
    exit;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    try {
        $action = (string)($_POST['action'] ?? '');
        $file = (string)($_POST['file'] ?? '');
        $csrf = (string)($_POST['csrf'] ?? '');

        if (!hpa_validate_csrf($csrf)) {
            throw new RuntimeException('Security token expired. Reload and try again.');
        }

        if ($action === 'download') {
            hpa_stream_download($file);
            exit;
        }

        if ($action === 'delete') {
            $path = hpa_safe_path($file);
            if (!@unlink($path)) {
                throw new RuntimeException('Unable to delete selected package.');
            }
            $notice = 'Deleted package: ' . $file;
        }
    } catch (Throwable $e) {
        $error = $e->getMessage();
    }
}

$csrf = hpa_csrf_token();
$dir = hpa_package_dir();
$packages = hpa_list_packages();

opsui_shell_begin([
    'title' => 'Handoff Package Archive',
    'page_title' => 'Handoff Package Archive',
    'active_section' => 'Deployment',
    'breadcrumbs' => 'Αρχική / Διαχειριστικό / Handoff Package Archive',
    'safe_notice' => 'Admin-only private package archive. This page only lists, downloads, or deletes generated handoff ZIPs from the private app folder.',
]);
?>
<section class="card hero neutral">
    <h1>Safe handoff package archive</h1>
    <p>Review and download handoff packages generated by the CLI runner. Packages remain outside the public webroot until an admin explicitly downloads them.</p>
    <div>
        <?= opsui_badge('ADMIN ONLY', 'good') ?>
        <?= opsui_badge('PRIVATE FOLDER', 'good') ?>
        <?= opsui_badge('NO DB EXPORT HERE', 'good') ?>
        <?= opsui_badge('NO SECRET DISPLAY', 'good') ?>
    </div>
    <div class="actions">
        <a class="btn" href="/ops/handoff-center.php">Handoff Center</a>
        <a class="btn dark" href="/ops/handoff-package-cli.php">CLI Builder Guide</a>
        <a class="btn dark" href="/ops/handoff-package-inspector.php">Package Inspector</a>
    </div>
</section>

<?php if ($notice !== ''): ?>
<section class="card" style="border-left:6px solid #07875a;">
    <h2>Done</h2>
    <p class="goodline"><strong><?= opsui_h($notice) ?></strong></p>
</section>
<?php endif; ?>

<?php if ($error !== ''): ?>
<section class="card" style="border-left:6px solid #b42318;">
    <h2>Archive action error</h2>
    <p class="badline"><strong><?= opsui_h($error) ?></strong></p>
</section>
<?php endif; ?>

<section class="card">
    <h2>Private archive status</h2>
    <div class="grid">
        <?= opsui_metric(count($packages), 'Generated packages') ?>
        <?= opsui_metric(is_dir($dir) ? 'YES' : 'NO', 'Archive directory exists') ?>
        <?= opsui_metric(is_writable($dir) ? 'YES' : 'NO', 'Archive directory writable') ?>
    </div>
    <p class="small">Private archive path: <code><?= opsui_h($dir) ?></code></p>
    <div class="safety" style="margin-top:12px;">
        <strong>PRIVATE OPERATIONAL DATA.</strong>
        Any package marked WITH DATABASE contains <code>DATABASE_EXPORT.sql</code> and may include operational/customer data. Do not commit it to GitHub unless it has been intentionally sanitized.
    </div>
</section>

<section class="card">
    <h2>Generated packages</h2>
    <?php if (!$packages): ?>
        <p>No generated handoff packages found yet.</p>
        <p class="small">Create one from SSH/cPanel Terminal:</p>
        <pre style="white-space:pre-wrap;background:#0b1220;color:#dbeafe;padding:12px;border-radius:8px;overflow:auto;">php /home/cabnet/gov.cabnet.app_app/cli/build_safe_handoff_package.php --json</pre>
    <?php else: ?>
        <div class="table-wrap">
            <table>
                <thead>
                    <tr>
                        <th>Package</th>
                        <th>Type</th>
                        <th>Size</th>
                        <th>Modified</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($packages as $pkg): ?>
                    <tr>
                        <td><code><?= opsui_h((string)$pkg['name']) ?></code></td>
                        <td><?= opsui_badge(!empty($pkg['with_db']) ? 'WITH DATABASE' : 'NO DATABASE', !empty($pkg['with_db']) ? 'warn' : 'good') ?></td>
                        <td><?= opsui_h(hpa_bytes((int)$pkg['size'])) ?></td>
                        <td><?= opsui_h(date('Y-m-d H:i:s T', (int)$pkg['mtime'])) ?></td>
                        <td>
                            <div style="display:flex;gap:8px;flex-wrap:wrap;">
                                <form method="post" action="/ops/handoff-package-archive.php">
                                    <input type="hidden" name="csrf" value="<?= opsui_h($csrf) ?>">
                                    <input type="hidden" name="action" value="download">
                                    <input type="hidden" name="file" value="<?= opsui_h((string)$pkg['name']) ?>">
                                    <button class="btn green" type="submit">Download</button>
                                </form>
                                <form method="post" action="/ops/handoff-package-archive.php" onsubmit="return confirm('Delete this generated handoff package from the private archive?');">
                                    <input type="hidden" name="csrf" value="<?= opsui_h($csrf) ?>">
                                    <input type="hidden" name="action" value="delete">
                                    <input type="hidden" name="file" value="<?= opsui_h((string)$pkg['name']) ?>">
                                    <button class="btn dark" type="submit">Delete</button>
                                </form>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php endif; ?>
</section>

<section class="two">
    <div class="card">
        <h2>Recommended workflow</h2>
        <ol class="list">
            <li>Run the CLI builder from SSH/cPanel Terminal.</li>
            <li>Open this archive page.</li>
            <li>Download the newest package.</li>
            <li>Store it privately; do not commit database exports.</li>
            <li>Delete old packages when no longer needed.</li>
        </ol>
    </div>
    <div class="card">
        <h2>CLI commands</h2>
        <pre style="white-space:pre-wrap;background:#0b1220;color:#dbeafe;padding:12px;border-radius:8px;overflow:auto;">php /home/cabnet/gov.cabnet.app_app/cli/build_safe_handoff_package.php --json

php /home/cabnet/gov.cabnet.app_app/cli/build_safe_handoff_package.php --no-db --json

php /home/cabnet/gov.cabnet.app_app/cli/build_safe_handoff_package.php --cleanup --keep-days=7</pre>
    </div>
</section>
<?php opsui_shell_end(); ?>
