<?php
/**
 * gov.cabnet.app — Mobile Submit Evidence Log
 *
 * Admin-only log for sanitized evidence JSON generated by the future mobile/server-side
 * EDXEIX submit dry-run workflow. This page never calls EDXEIX and never stores raw
 * email bodies, cookies, sessions, token values, credentials, or real config values.
 */

declare(strict_types=1);

header('Content-Type: text/html; charset=utf-8');
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Pragma: no-cache');
header('X-Robots-Tag: noindex,nofollow', true);

if (session_status() !== PHP_SESSION_ACTIVE) {
    session_start();
}

require_once __DIR__ . '/_shell.php';

function msel_h(mixed $value): string
{
    return htmlspecialchars((string)$value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

function msel_csrf(): string
{
    if (empty($_SESSION['mobile_submit_evidence_log_csrf']) || !is_string($_SESSION['mobile_submit_evidence_log_csrf'])) {
        $_SESSION['mobile_submit_evidence_log_csrf'] = bin2hex(random_bytes(32));
    }
    return $_SESSION['mobile_submit_evidence_log_csrf'];
}

function msel_validate_csrf(string $token): bool
{
    return isset($_SESSION['mobile_submit_evidence_log_csrf'])
        && is_string($_SESSION['mobile_submit_evidence_log_csrf'])
        && hash_equals($_SESSION['mobile_submit_evidence_log_csrf'], $token);
}

function msel_app_context(?string &$error = null): ?array
{
    static $ctx = null;
    static $loaded = false;
    static $loadError = null;

    if ($loaded) {
        $error = $loadError;
        return is_array($ctx) ? $ctx : null;
    }

    $loaded = true;
    $bootstrap = dirname(__DIR__, 3) . '/gov.cabnet.app_app/src/bootstrap.php';
    if (!is_file($bootstrap)) {
        $loadError = 'Private app bootstrap not found.';
        $error = $loadError;
        return null;
    }

    try {
        $ctx = require $bootstrap;
        if (!is_array($ctx)) {
            throw new RuntimeException('Private app bootstrap did not return a context array.');
        }
        $error = null;
        return $ctx;
    } catch (Throwable $e) {
        $loadError = $e->getMessage();
        $error = $loadError;
        return null;
    }
}

function msel_db(?string &$error = null): ?mysqli
{
    $ctx = msel_app_context($error);
    if (!$ctx || !isset($ctx['db']) || !method_exists($ctx['db'], 'connection')) {
        $error = $error ?: 'Private DB context is unavailable.';
        return null;
    }
    try {
        $db = $ctx['db']->connection();
        if (!$db instanceof mysqli) {
            throw new RuntimeException('DB context did not return mysqli.');
        }
        return $db;
    } catch (Throwable $e) {
        $error = $e->getMessage();
        return null;
    }
}

function msel_table_exists(mysqli $db, string $table): bool
{
    try {
        $stmt = $db->prepare('SELECT TABLE_NAME FROM information_schema.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ? LIMIT 1');
        $stmt->bind_param('s', $table);
        $stmt->execute();
        return (bool)$stmt->get_result()->fetch_assoc();
    } catch (Throwable) {
        return false;
    }
}

function msel_current_user(): array
{
    if (function_exists('opsui_current_user')) {
        return opsui_current_user();
    }
    $user = $_SESSION['ops_user'] ?? [];
    return is_array($user) ? $user : [];
}

function msel_is_admin(): bool
{
    if (function_exists('opsui_is_admin')) {
        return opsui_is_admin();
    }
    $user = msel_current_user();
    return strtolower((string)($user['role'] ?? 'operator')) === 'admin';
}

function msel_badge(string $text, string $type = 'neutral'): string
{
    if (function_exists('opsui_badge')) {
        return opsui_badge($text, $type);
    }
    return '<span class="badge badge-' . msel_h($type) . '">' . msel_h($text) . '</span>';
}

function msel_contains_forbidden_content(string $json, array &$matches): bool
{
    $patterns = [
        '/Operator:\s*/i' => 'raw_bolt_email_operator_line',
        '/Customer mobile:\s*/i' => 'raw_bolt_email_customer_mobile_line',
        '/Pickup:\s*/i' => 'raw_bolt_email_pickup_line',
        '/Drop-off:\s*/i' => 'raw_bolt_email_dropoff_line',
        '/PHPSESSID|laravel_session|remember_web|XSRF-TOKEN/i' => 'session_or_cookie_pattern',
        '/BEGIN\s+(RSA|OPENSSH|PRIVATE)\s+KEY/i' => 'private_key_pattern',
        '/("|\')?(password|passwd|secret|credential|private_key|cookie_value|session_value|csrf_token_value)("|\')?\s*[:=]/i' => 'secret_like_key_pattern',
    ];

    foreach ($patterns as $pattern => $label) {
        if (preg_match($pattern, $json)) {
            $matches[] = $label;
        }
    }

    return $matches !== [];
}

/**
 * @param mixed $value
 * @return mixed
 */
function msel_sanitize_value(mixed $value, string $keyPath = ''): mixed
{
    if (is_array($value)) {
        $out = [];
        foreach ($value as $key => $child) {
            $keyText = (string)$key;
            $childPath = $keyPath === '' ? $keyText : $keyPath . '.' . $keyText;
            if (msel_is_sensitive_json_key($keyText, $childPath)) {
                $out[$key] = '__REDACTED_BY_EVIDENCE_LOG__';
            } else {
                $out[$key] = msel_sanitize_value($child, $childPath);
            }
        }
        return $out;
    }

    if (is_string($value)) {
        if (preg_match('/PHPSESSID|laravel_session|remember_web|XSRF-TOKEN|BEGIN\s+(RSA|OPENSSH|PRIVATE)\s+KEY/i', $value)) {
            return '__REDACTED_BY_EVIDENCE_LOG__';
        }
        if (strlen($value) > 20000) {
            return substr($value, 0, 20000) . '\n__TRUNCATED_BY_EVIDENCE_LOG__';
        }
    }

    return $value;
}

function msel_is_sensitive_json_key(string $key, string $path): bool
{
    $name = strtolower($key);
    $full = strtolower($path);

    $allowed = [
        'csrf_field_name',
        'csrf_field_name_from_capture',
        'csrf_field_name_detected',
        'raw_email_sha256',
        'email_sha256',
        'source_email_sha256',
    ];
    if (in_array($name, $allowed, true)) {
        return false;
    }

    if (in_array($name, ['raw_email', 'raw_email_text', 'email_text', 'source_email_text', 'message_body'], true)) {
        return true;
    }

    return (bool)preg_match('/(^|_)(password|passwd|secret|credential|cookie|session|csrf_token|token_value|private_key)(_|$)/i', $name)
        || str_contains($full, 'raw_email_text')
        || str_contains($full, 'email_text');
}

/** @param mixed $node */
function msel_find_first($node, array $keys): string
{
    if (!is_array($node)) {
        return '';
    }
    foreach ($keys as $key) {
        if (array_key_exists($key, $node) && !is_array($node[$key]) && trim((string)$node[$key]) !== '') {
            return trim((string)$node[$key]);
        }
    }
    foreach ($node as $child) {
        if (is_array($child)) {
            $found = msel_find_first($child, $keys);
            if ($found !== '') {
                return $found;
            }
        }
    }
    return '';
}

function msel_normalize_json(string $raw, array &$meta, array &$errors): string
{
    $raw = trim($raw);
    if ($raw === '') {
        $errors[] = 'Evidence JSON is empty.';
        return '';
    }

    $matches = [];
    if (msel_contains_forbidden_content($raw, $matches)) {
        $errors[] = 'Evidence JSON appears to contain raw email text or secret/session patterns: ' . implode(', ', array_unique($matches));
        return '';
    }

    $decoded = json_decode($raw, true);
    if (!is_array($decoded)) {
        $errors[] = 'Evidence JSON could not be parsed: ' . json_last_error_msg();
        return '';
    }

    $sanitized = msel_sanitize_value($decoded);
    $json = json_encode($sanitized, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    if (!is_string($json) || $json === '') {
        $errors[] = 'Sanitized evidence JSON could not be encoded.';
        return '';
    }

    $meta = [
        'evidence_sha256' => hash('sha256', $json),
        'email_sha256' => msel_find_first($sanitized, ['raw_email_sha256', 'email_sha256', 'source_email_sha256']),
        'final_status' => msel_find_first($sanitized, ['final_status', 'trial_status', 'decision', 'status']),
        'lessor_id' => msel_find_first($sanitized, ['lessor_id', 'lessorId']),
        'driver_id' => msel_find_first($sanitized, ['driver_id', 'driverId']),
        'vehicle_id' => msel_find_first($sanitized, ['vehicle_id', 'vehicleId']),
        'starting_point_id' => msel_find_first($sanitized, ['starting_point_id', 'startingPointId']),
    ];

    return $json;
}

function msel_fetch_recent(mysqli $db): array
{
    if (!msel_table_exists($db, 'mobile_submit_evidence_log')) {
        return [];
    }
    $rows = [];
    $res = $db->query('SELECT id, evidence_sha256, email_sha256, source_label, final_status, lessor_id, driver_id, vehicle_id, starting_point_id, notes, created_by_username, created_at FROM mobile_submit_evidence_log ORDER BY id DESC LIMIT 100');
    if ($res) {
        while ($row = $res->fetch_assoc()) {
            $rows[] = $row;
        }
    }
    return $rows;
}

function msel_download_json(mysqli $db, int $id): void
{
    $stmt = $db->prepare('SELECT id, evidence_sha256, evidence_json FROM mobile_submit_evidence_log WHERE id = ? LIMIT 1');
    $stmt->bind_param('i', $id);
    $stmt->execute();
    $row = $stmt->get_result()->fetch_assoc();
    if (!$row) {
        http_response_code(404);
        echo 'Not found.';
        exit;
    }
    $name = 'mobile_submit_evidence_' . (int)$row['id'] . '_' . substr((string)$row['evidence_sha256'], 0, 12) . '.json';
    header_remove('Content-Type');
    header('Content-Type: application/json; charset=utf-8');
    header('Content-Disposition: attachment; filename="' . $name . '"');
    header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
    echo (string)$row['evidence_json'];
    exit;
}

$dbError = null;
$db = msel_db($dbError);
$tableReady = $db instanceof mysqli && msel_table_exists($db, 'mobile_submit_evidence_log');
$csrf = msel_csrf();
$message = '';
$messageType = 'neutral';
$postedJson = '';
$postedNotes = '';
$postedSource = '';

if ($db && $tableReady && isset($_GET['download'])) {
    msel_download_json($db, max(0, (int)$_GET['download']));
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $postedJson = (string)($_POST['evidence_json'] ?? '');
    $postedNotes = trim((string)($_POST['notes'] ?? ''));
    $postedSource = trim((string)($_POST['source_label'] ?? ''));

    try {
        if (!msel_is_admin()) {
            throw new RuntimeException('Admin role is required to save evidence.');
        }
        if (!msel_validate_csrf((string)($_POST['csrf'] ?? ''))) {
            throw new RuntimeException('Security token expired. Please reload and try again.');
        }
        if (!$db) {
            throw new RuntimeException('DB unavailable: ' . (string)$dbError);
        }
        if (!$tableReady) {
            throw new RuntimeException('Table mobile_submit_evidence_log is not installed. Run the Phase 59 SQL migration first.');
        }

        $meta = [];
        $errors = [];
        $normalized = msel_normalize_json($postedJson, $meta, $errors);
        if ($errors !== []) {
            throw new RuntimeException(implode(' ', $errors));
        }

        $user = msel_current_user();
        $userId = (int)($user['id'] ?? 0);
        $username = trim((string)($user['username'] ?? $user['display_name'] ?? ''));
        $source = $postedSource !== '' ? $postedSource : 'mobile-submit-evidence.php';

        $stmt = $db->prepare("INSERT INTO mobile_submit_evidence_log
            (evidence_sha256, email_sha256, source_label, final_status, lessor_id, driver_id, vehicle_id, starting_point_id, evidence_json, notes, created_by_user_id, created_by_username, created_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW())
            ON DUPLICATE KEY UPDATE
                source_label = VALUES(source_label),
                final_status = VALUES(final_status),
                lessor_id = VALUES(lessor_id),
                driver_id = VALUES(driver_id),
                vehicle_id = VALUES(vehicle_id),
                starting_point_id = VALUES(starting_point_id),
                evidence_json = VALUES(evidence_json),
                notes = VALUES(notes),
                created_by_user_id = VALUES(created_by_user_id),
                created_by_username = VALUES(created_by_username),
                created_at = NOW()");
        $stmt->bind_param(
            'ssssssssssis',
            $meta['evidence_sha256'],
            $meta['email_sha256'],
            $source,
            $meta['final_status'],
            $meta['lessor_id'],
            $meta['driver_id'],
            $meta['vehicle_id'],
            $meta['starting_point_id'],
            $normalized,
            $postedNotes,
            $userId,
            $username
        );
        $stmt->execute();

        $message = 'Sanitized evidence saved. SHA-256: ' . $meta['evidence_sha256'];
        $messageType = 'good';
        $postedJson = '';
        $postedNotes = '';
        $postedSource = '';
    } catch (Throwable $e) {
        $message = $e->getMessage();
        $messageType = 'bad';
    }
}

$recent = $db ? msel_fetch_recent($db) : [];

opsui_shell_begin([
    'title' => 'Mobile Submit Evidence Log',
    'page_title' => 'Mobile Submit Evidence Log',
    'active_section' => 'Mobile Submit',
    'breadcrumbs' => 'Αρχική / Mobile Submit / Evidence Log',
    'safe_notice' => 'Admin-only sanitized evidence log. It stores dry-run JSON evidence only and does not call EDXEIX or enable live submit.',
    'force_safe_notice' => true,
]);
?>
<style>
.evidence-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(320px,.55fr);gap:18px}.evidence-card{background:#fff;border:1px solid #d8dde7;border-radius:4px;padding:18px 20px;box-shadow:0 6px 18px rgba(26,33,52,.06)}.evidence-json{min-height:340px;font-family:Consolas,Menlo,Monaco,monospace;font-size:13px}.evidence-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:12px}.evidence-meta{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.evidence-warning{background:#fff7ed;border:1px solid #fed7aa;border-left:6px solid #d97706;border-radius:4px;padding:12px 14px;margin:12px 0;color:#9a3412}@media(max-width:980px){.evidence-grid,.evidence-meta{grid-template-columns:1fr}.evidence-card{padding:15px}.evidence-actions .btn{width:100%;text-align:center}}</style>

<section class="card hero warn">
    <h1>Mobile Submit Evidence Log</h1>
    <p>Store sanitized dry-run evidence snapshots from the mobile/server-side EDXEIX submit workflow. This is for debugging, governance, and future-session continuity only.</p>
    <div>
        <?= msel_badge('ADMIN ONLY', msel_is_admin() ? 'good' : 'warn') ?>
        <?= msel_badge('NO LIVE SUBMIT', 'good') ?>
        <?= msel_badge('NO EDXEIX CALL', 'good') ?>
        <?= msel_badge('SANITIZED JSON ONLY', 'good') ?>
    </div>
</section>

<?php if ($message !== ''): ?>
<section class="card">
    <?= function_exists('opsui_flash') ? opsui_flash($message, $messageType) : '<p>' . msel_h($message) . '</p>' ?>
</section>
<?php endif; ?>

<section class="evidence-meta">
    <div class="metric"><strong><?= $db ? 'OK' : 'NO' ?></strong><span>DB context</span></div>
    <div class="metric"><strong><?= $tableReady ? 'YES' : 'NO' ?></strong><span>evidence table installed</span></div>
    <div class="metric"><strong><?= count($recent) ?></strong><span>recent records shown</span></div>
    <div class="metric"><strong><?= msel_is_admin() ? 'YES' : 'NO' ?></strong><span>admin write access</span></div>
</section>

<?php if (!$tableReady): ?>
<section class="card" style="border-left:6px solid #b42318;">
    <h2>SQL migration required</h2>
    <p class="badline"><strong>The table <code>mobile_submit_evidence_log</code> is not installed yet.</strong></p>
    <pre><code>mysql -u cabnet_gov -p cabnet_gov &lt; /home/cabnet/gov.cabnet.app_sql/2026_05_12_mobile_submit_evidence_log.sql</code></pre>
</section>
<?php endif; ?>

<section class="evidence-grid">
    <div class="evidence-card">
        <h2>Save sanitized evidence JSON</h2>
        <p class="small">Paste JSON from <code>/ops/mobile-submit-evidence.php</code>. This page blocks obvious raw email text and secret/session patterns.</p>
        <form method="post" action="/ops/mobile-submit-evidence-log.php" autocomplete="off">
            <input type="hidden" name="csrf" value="<?= msel_h($csrf) ?>">
            <div class="field" style="margin-bottom:10px;">
                <label for="source_label">Source label</label>
                <input id="source_label" name="source_label" value="<?= msel_h($postedSource) ?>" placeholder="mobile-submit-evidence.php / live test / note">
            </div>
            <div class="field" style="margin-bottom:10px;">
                <label for="evidence_json">Sanitized evidence JSON</label>
                <textarea class="evidence-json" id="evidence_json" name="evidence_json" placeholder="Paste sanitized evidence JSON here..." <?= !msel_is_admin() || !$tableReady ? 'disabled' : '' ?>><?= msel_h($postedJson) ?></textarea>
            </div>
            <div class="field" style="margin-bottom:10px;">
                <label for="notes">Notes</label>
                <textarea id="notes" name="notes" style="min-height:90px;" placeholder="Optional operator/admin notes" <?= !msel_is_admin() || !$tableReady ? 'disabled' : '' ?>><?= msel_h($postedNotes) ?></textarea>
            </div>
            <div class="evidence-actions">
                <button class="btn green" type="submit" <?= !msel_is_admin() || !$tableReady ? 'disabled' : '' ?>>Save sanitized evidence</button>
                <a class="btn dark" href="/ops/mobile-submit-evidence.php">Open Evidence Snapshot</a>
                <a class="btn dark" href="/ops/mobile-submit-trial-run.php">Open Trial Run</a>
            </div>
        </form>
    </div>

    <aside class="evidence-card">
        <h2>Rules</h2>
        <div class="evidence-warning"><strong>Do not paste raw Bolt email text here.</strong> Use the sanitized JSON from the Evidence Snapshot page.</div>
        <ul class="list">
            <li>Allowed: parsed safe fields, IDs, hashes, dry-run status, preflight result, validator result.</li>
            <li>Blocked: raw email body, cookies, sessions, CSRF token values, credentials, private keys, real config values.</li>
            <li>Evidence records are for debugging/governance only.</li>
            <li>No live EDXEIX submit exists on this page.</li>
        </ul>
        <h3>Related pages</h3>
        <div class="actions">
            <a class="btn dark" href="/ops/mobile-submit-center.php">Mobile Submit Center</a>
            <a class="btn dark" href="/ops/mobile-submit-gates.php">Submit Gates</a>
            <a class="btn dark" href="/ops/edxeix-submit-payload-validator.php">Payload Validator</a>
        </div>
    </aside>
</section>

<section class="card">
    <h2>Recent evidence records</h2>
    <div class="table-wrap">
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Created</th>
                    <th>Status</th>
                    <th>Source</th>
                    <th>IDs</th>
                    <th>Email hash</th>
                    <th>Evidence hash</th>
                    <th>User</th>
                    <th>JSON</th>
                </tr>
            </thead>
            <tbody>
            <?php if (!$recent): ?>
                <tr><td colspan="9" class="small">No evidence records yet.</td></tr>
            <?php endif; ?>
            <?php foreach ($recent as $row): ?>
                <tr>
                    <td><?= msel_h($row['id'] ?? '') ?></td>
                    <td><?= msel_h($row['created_at'] ?? '') ?></td>
                    <td><?= msel_badge((string)($row['final_status'] ?: 'unknown'), str_contains(strtolower((string)($row['final_status'] ?? '')), 'ready') ? 'good' : 'warn') ?></td>
                    <td><?= msel_h($row['source_label'] ?? '') ?></td>
                    <td>
                        <div>L: <strong><?= msel_h($row['lessor_id'] ?? '-') ?></strong></div>
                        <div>D: <strong><?= msel_h($row['driver_id'] ?? '-') ?></strong></div>
                        <div>V: <strong><?= msel_h($row['vehicle_id'] ?? '-') ?></strong></div>
                        <div>SP: <strong><?= msel_h($row['starting_point_id'] ?? '-') ?></strong></div>
                    </td>
                    <td><code><?= msel_h(substr((string)($row['email_sha256'] ?? ''), 0, 16)) ?></code></td>
                    <td><code><?= msel_h(substr((string)($row['evidence_sha256'] ?? ''), 0, 16)) ?></code></td>
                    <td><?= msel_h($row['created_by_username'] ?? '') ?></td>
                    <td><a class="btn light" href="/ops/mobile-submit-evidence-log.php?download=<?= (int)($row['id'] ?? 0) ?>">Download</a></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</section>

<?php opsui_shell_end(); ?>
