<?php
/**
 * gov.cabnet.app — Safe Handoff Package Builder
 *
 * Builds an admin-only downloadable handoff ZIP from the live server layout.
 * The builder excludes obvious secrets/logs/cache/mail/session material and writes
 * sanitized config placeholders instead of copying real server-only config files.
 *
 * Safety contract:
 * - Does not call Bolt.
 * - Does not call EDXEIX.
 * - Does not call AADE.
 * - Does not expose real config values.
 * - Does not store generated ZIPs in the public webroot.
 */

declare(strict_types=1);

namespace Bridge\Support;

use DateTimeImmutable;
use FilesystemIterator;
use mysqli;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use RuntimeException;
use Throwable;
use ZipArchive;

final class SafeHandoffPackageBuilder
{
    /** @var array<string,string> */
    private array $paths;

    /** @var list<string> */
    private array $manifest = [];

    /** @param array<string,string> $paths */
    public function __construct(array $paths)
    {
        $this->paths = $paths;
    }

    /**
     * Builds a temporary ZIP and returns its absolute path.
     * Caller is responsible for streaming and deleting it.
     *
     * @param array<string,mixed> $options
     */
    public function build(array $options = []): string
    {
        if (!class_exists(ZipArchive::class)) {
            throw new RuntimeException('PHP ZipArchive extension is not available.');
        }

        @set_time_limit(300);

        $stamp = (new DateTimeImmutable('now'))->format('Ymd_His');
        $tmpBase = rtrim(sys_get_temp_dir(), DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR;
        $zipPath = $tmpBase . 'gov_cabnet_safe_handoff_' . $stamp . '_' . bin2hex(random_bytes(4)) . '.zip';

        $zip = new ZipArchive();
        if ($zip->open($zipPath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
            throw new RuntimeException('Unable to create temporary handoff ZIP.');
        }

        try {
            $this->manifest = [];
            $this->addText($zip, 'PACKAGE_MANIFEST.md', $this->buildPackageManifestHeader());

            $this->addProjectDirectory($zip, 'publicRoot', 'public_html/gov.cabnet.app');
            $this->addProjectDirectory($zip, 'appRoot', 'gov.cabnet.app_app');
            $this->addProjectDirectory($zip, 'sqlRoot', 'gov.cabnet.app_sql');
            $this->addProjectDirectory($zip, 'docsRoot', 'docs');
            $this->addFirefoxTools($zip);
            $this->addRootDocumentationFiles($zip);
            $this->addSanitizedConfigExamples($zip);

            if (($options['include_database'] ?? true) !== false) {
                $this->addDatabaseExport($zip);
            }

            $this->addText($zip, 'PACKAGE_MANIFEST.md', $this->buildPackageManifestHeader() . "\n\n## Included files\n\n" . implode("\n", $this->manifest) . "\n");
        } catch (Throwable $e) {
            $zip->close();
            @unlink($zipPath);
            throw $e;
        }

        $zip->close();

        return $zipPath;
    }

    private function buildPackageManifestHeader(): string
    {
        $generated = (new DateTimeImmutable('now'))->format('Y-m-d H:i:s T');
        return <<<MD
# gov.cabnet.app Safe Handoff Package

Generated: {$generated}

This ZIP was generated by `/ops/handoff-center.php` for Andreas.

## Safety notes

- Real server-only config files are not copied.
- Sanitized config placeholders are written under `gov.cabnet.app_config_examples/`.
- Obvious logs, sessions, cache, temporary files, mailboxes, compressed archives, and backup directories are excluded.
- The database export is included because it was explicitly requested. Treat this ZIP as private operational data and do not commit the database export to GitHub unless intentionally sanitized.
- No Bolt, EDXEIX, or AADE calls are made by the package builder.

MD;
    }

    private function addProjectDirectory(ZipArchive $zip, string $pathKey, string $zipPrefix): void
    {
        $source = $this->paths[$pathKey] ?? '';
        if ($source === '' || !is_dir($source)) {
            $this->addText($zip, $zipPrefix . '/_MISSING_DIRECTORY.txt', "Directory not found on server: {$source}\n");
            return;
        }
        $this->addDirectory($zip, $source, $zipPrefix);
    }

    private function addDirectory(ZipArchive $zip, string $source, string $zipPrefix): void
    {
        $sourceReal = realpath($source);
        if ($sourceReal === false || !is_dir($sourceReal) || !is_readable($sourceReal)) {
            return;
        }

        $this->addDirectoryRecursive($zip, $sourceReal, $zipPrefix, '');
    }

    private function addDirectoryRecursive(ZipArchive $zip, string $sourceReal, string $zipPrefix, string $relativeDir): void
    {
        $dir = $relativeDir === '' ? $sourceReal : $sourceReal . DIRECTORY_SEPARATOR . str_replace('/', DIRECTORY_SEPARATOR, $relativeDir);
        if (!is_dir($dir) || !is_readable($dir)) {
            return;
        }

        $items = @scandir($dir);
        if (!is_array($items)) {
            return;
        }

        foreach ($items as $name) {
            if ($name === '.' || $name === '..') {
                continue;
            }

            $relative = ltrim($relativeDir . '/' . $name, '/');
            $path = $dir . DIRECTORY_SEPARATOR . $name;

            if (is_link($path)) {
                continue;
            }

            $isDir = is_dir($path);
            if ($this->shouldExclude($relative, $isDir)) {
                continue;
            }

            $zipName = trim($zipPrefix . '/' . $relative, '/');

            if ($isDir) {
                if (!is_readable($path)) {
                    continue;
                }
                $zip->addEmptyDir($zipName);
                $this->addDirectoryRecursive($zip, $sourceReal, $zipPrefix, $relative);
                continue;
            }

            if (!is_file($path) || !is_readable($path)) {
                continue;
            }

            $zip->addFile($path, $zipName);
            $this->manifest[] = '- `' . $zipName . '`';
        }
    }

    private function shouldExclude(string $relative, bool $isDir): bool
    {
        $path = '/' . strtolower(str_replace('\\', '/', $relative));
        $base = strtolower(basename($relative));

        $excludedSegments = [
            '/.git/', '/.svn/', '/.hg/', '/node_modules/', '/vendor/', '/cache/', '/tmp/', '/temp/',
            '/sessions/', '/session/', '/mail/', '/maildir/', '/logs/', '/log/', '/backup/', '/backups/',
            '/wordpress-backups/', '/.cpanel/', '/.trash/', '/access-logs/', '/storage/artifacts/', '/storage/cache/',
            '/storage/logs/', '/storage/tmp/', '/storage/temp/', '/var/', '/handoff-packages/',
        ];
        foreach ($excludedSegments as $segment) {
            if (str_contains($path . ($isDir ? '/' : ''), $segment)) {
                return true;
            }
        }

        $excludedNames = [
            '.env', '.env.local', '.env.production', '.user.ini.bak', 'error_log', 'debug.log',
            'session.sqlite', 'cookies.txt', 'cookie.txt', 'id_rsa', 'id_rsa.pub',
        ];
        if (in_array($base, $excludedNames, true)) {
            return true;
        }

        if (preg_match('/\.(log|zip|tar|tgz|gz|bz2|7z|rar|bak|backup|old|tmp|swp|swo)$/i', $base)) {
            return true;
        }

        if (preg_match('/(secret|credential|cookie|session_dump|raw_dump|private_key)/i', $relative)) {
            return true;
        }

        return false;
    }

    private function addFirefoxTools(ZipArchive $zip): void
    {
        $toolsRoot = $this->paths['toolsRoot'] ?? '';
        if ($toolsRoot === '' || !is_dir($toolsRoot)) {
            return;
        }

        $items = @scandir($toolsRoot);
        if (!is_array($items)) {
            return;
        }

        foreach ($items as $item) {
            if ($item === '.' || $item === '..') {
                continue;
            }
            $full = rtrim($toolsRoot, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR . $item;
            if (!is_dir($full)) {
                continue;
            }
            $name = strtolower($item);
            if (str_contains($name, 'firefox') || str_contains($name, 'edxeix')) {
                $this->addDirectory($zip, $full, 'tools/' . $item);
            }
        }
    }

    private function addRootDocumentationFiles(ZipArchive $zip): void
    {
        $homeRoot = $this->paths['homeRoot'] ?? '';
        if ($homeRoot === '' || !is_dir($homeRoot)) {
            return;
        }

        $files = [
            'HANDOFF.md',
            'CONTINUE_PROMPT.md',
            'README.md',
            'SCOPE.md',
            'DEPLOYMENT.md',
            'SECURITY.md',
            'PROJECT_FILE_MANIFEST.md',
            'PATCH_README.md',
            '.gitignore',
        ];

        foreach ($files as $file) {
            $path = rtrim($homeRoot, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR . $file;
            if (is_file($path) && is_readable($path) && !$this->shouldExclude($file, false)) {
                $zip->addFile($path, $file);
                $this->manifest[] = '- `' . $file . '`';
            }
        }
    }

    private function addSanitizedConfigExamples(ZipArchive $zip): void
    {
        $configRoot = $this->paths['configRoot'] ?? '';
        $notice = <<<TXT
This directory contains sanitized placeholders generated from /home/cabnet/gov.cabnet.app_config.
Real server-only config files were not copied into this ZIP.
Replace placeholder values only on the server. Never commit real credentials.
TXT;
        $this->addText($zip, 'gov.cabnet.app_config_examples/README_SANITIZED_CONFIG.txt', $notice . "\n");

        if ($configRoot === '' || !is_dir($configRoot)) {
            $this->addText($zip, 'gov.cabnet.app_config_examples/_MISSING_CONFIG_DIRECTORY.txt', "Config directory not found on server.\n");
            return;
        }

        $iterator = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($configRoot, FilesystemIterator::SKIP_DOTS),
            RecursiveIteratorIterator::SELF_FIRST
        );

        foreach ($iterator as $item) {
            if (!$item->isFile() || !$item->isReadable() || $item->isLink()) {
                continue;
            }
            $relative = ltrim(str_replace('\\', '/', substr($item->getPathname(), strlen(realpath($configRoot) ?: $configRoot))), '/');
            if ($relative === '' || $this->shouldExclude($relative, false)) {
                continue;
            }
            $base = basename($relative);
            $exampleName = preg_replace('/\.php$/i', '.example.php', $base) ?: ($base . '.example');
            $content = $this->buildSanitizedConfigStub($item->getPathname(), $relative);
            $this->addText($zip, 'gov.cabnet.app_config_examples/' . $exampleName, $content);
        }
    }

    private function buildSanitizedConfigStub(string $path, string $relative): string
    {
        $raw = (string)@file_get_contents($path);
        $keys = [];
        if ($raw !== '') {
            if (preg_match_all('/[\'\"]([A-Za-z0-9_.-]+)[\'\"]\s*=>/u', $raw, $m)) {
                foreach ($m[1] as $key) {
                    $keys[$key] = true;
                }
            }
            if (preg_match_all('/(?:define\s*\(|putenv\s*\()\s*[\'\"]([A-Za-z0-9_.-]+)[\'\"]/iu', $raw, $m2)) {
                foreach ($m2[1] as $key) {
                    $keys[$key] = true;
                }
            }
        }

        $lines = [];
        $lines[] = '<?php';
        $lines[] = '/**';
        $lines[] = ' * Sanitized placeholder generated from server-only config: ' . $relative;
        $lines[] = ' * Real values were intentionally removed. Do not commit real credentials.';
        $lines[] = ' */';
        $lines[] = 'return [';
        $lines[] = "    '__sanitized_from' => '" . $this->phpString($relative) . "',";
        $lines[] = "    '__notice' => 'Real server-only values removed. Replace placeholders only on the server.',";
        $lines[] = "    'detected_keys' => [";

        if (!$keys) {
            $lines[] = "        '__NO_KEYS_DETECTED__' => '__RECREATE_SERVER_ONLY_CONFIG_MANUALLY__',";
        } else {
            foreach (array_keys($keys) as $key) {
                $placeholder = $this->isSensitiveKey($key) ? '__SERVER_ONLY_SECRET__' : '__REPLACE_ON_SERVER__';
                $lines[] = "        '" . $this->phpString($key) . "' => '" . $placeholder . "',";
            }
        }

        $lines[] = '    ],';
        $lines[] = '];';
        $lines[] = '';
        return implode("\n", $lines);
    }

    private function isSensitiveKey(string $key): bool
    {
        return (bool)preg_match('/pass|password|secret|token|key|credential|cookie|session|private|aade|api|smtp|mail|user|username/i', $key);
    }

    private function phpString(string $value): string
    {
        return str_replace(['\\', "'"], ['\\\\', "\\'"], $value);
    }

    private function addDatabaseExport(ZipArchive $zip): void
    {
        $bootstrap = $this->paths['bootstrap'] ?? '';
        if ($bootstrap === '' || !is_file($bootstrap)) {
            $this->addText($zip, 'DATABASE_EXPORT_NOT_CREATED.txt', "Private bootstrap was not found; database export was not created.\n");
            return;
        }

        $ctx = require $bootstrap;
        if (!is_array($ctx) || !isset($ctx['db']) || !method_exists($ctx['db'], 'connection')) {
            $this->addText($zip, 'DATABASE_EXPORT_NOT_CREATED.txt', "Private bootstrap did not return a usable DB context.\n");
            return;
        }

        $db = $ctx['db']->connection();
        if (!$db instanceof mysqli) {
            $this->addText($zip, 'DATABASE_EXPORT_NOT_CREATED.txt', "DB context did not return mysqli.\n");
            return;
        }

        $tmpSql = rtrim(sys_get_temp_dir(), DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR . 'gov_cabnet_db_export_' . bin2hex(random_bytes(4)) . '.sql';
        try {
            $this->writeDatabaseDump($db, $tmpSql);
            $zip->addFile($tmpSql, 'DATABASE_EXPORT.sql');
            $this->manifest[] = '- `DATABASE_EXPORT.sql`';
        } finally {
            // ZipArchive reads added files on close, so keep the temp file until shutdown.
            register_shutdown_function(static function () use ($tmpSql): void {
                if (is_file($tmpSql)) {
                    @unlink($tmpSql);
                }
            });
        }
    }

    private function writeDatabaseDump(mysqli $db, string $file): void
    {
        $fh = fopen($file, 'wb');
        if (!$fh) {
            throw new RuntimeException('Unable to create temporary database SQL export.');
        }

        try {
            $dbNameRow = $db->query('SELECT DATABASE() AS db_name');
            $dbName = '';
            if ($dbNameRow) {
                $row = $dbNameRow->fetch_assoc();
                $dbName = (string)($row['db_name'] ?? '');
            }

            fwrite($fh, "-- gov.cabnet.app safe handoff database export\n");
            fwrite($fh, "-- Generated: " . (new DateTimeImmutable('now'))->format('Y-m-d H:i:s T') . "\n");
            fwrite($fh, "-- Database: " . $dbName . "\n");
            fwrite($fh, "-- Treat as private operational data.\n\n");
            fwrite($fh, "SET NAMES utf8mb4;\nSET FOREIGN_KEY_CHECKS=0;\n\n");

            $tables = [];
            $res = $db->query("SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'");
            if ($res) {
                while ($row = $res->fetch_array(MYSQLI_NUM)) {
                    if (isset($row[0]) && is_string($row[0])) {
                        $tables[] = $row[0];
                    }
                }
            }

            foreach ($tables as $table) {
                if ($this->shouldSkipDatabaseTable($table)) {
                    fwrite($fh, "-- Skipped table by safety rule: " . $table . "\n\n");
                    continue;
                }

                $qt = $this->quoteIdentifier($table);
                fwrite($fh, "\n-- --------------------------------------------------------\n");
                fwrite($fh, "-- Table structure for {$qt}\n\n");
                fwrite($fh, "DROP TABLE IF EXISTS {$qt};\n");

                $createRes = $db->query('SHOW CREATE TABLE ' . $qt);
                if ($createRes) {
                    $createRow = $createRes->fetch_array(MYSQLI_NUM);
                    fwrite($fh, (string)($createRow[1] ?? '') . ";\n\n");
                }

                $dataRes = $db->query('SELECT * FROM ' . $qt);
                if (!$dataRes || $dataRes->num_rows === 0) {
                    continue;
                }

                $fields = [];
                $fieldInfo = $dataRes->fetch_fields();
                foreach ($fieldInfo as $field) {
                    $fields[] = $this->quoteIdentifier((string)$field->name);
                }
                $columnList = '(' . implode(',', $fields) . ')';

                fwrite($fh, "-- Data for {$qt}\n");
                while ($row = $dataRes->fetch_assoc()) {
                    $values = [];
                    foreach ($row as $value) {
                        if ($value === null) {
                            $values[] = 'NULL';
                        } else {
                            $values[] = "'" . $db->real_escape_string((string)$value) . "'";
                        }
                    }
                    fwrite($fh, 'INSERT INTO ' . $qt . ' ' . $columnList . ' VALUES (' . implode(',', $values) . ");\n");
                }
                fwrite($fh, "\n");
            }

            fwrite($fh, "SET FOREIGN_KEY_CHECKS=1;\n");
        } finally {
            fclose($fh);
        }
    }

    private function shouldSkipDatabaseTable(string $table): bool
    {
        // The user explicitly requested a database SQL export. Keep the dump broad,
        // but skip obvious ephemeral/session/cache tables if they appear.
        return (bool)preg_match('/(^sessions?$|cache|tmp|temporary|password_reset|remember_tokens?)/i', $table);
    }

    private function quoteIdentifier(string $name): string
    {
        return '`' . str_replace('`', '``', $name) . '`';
    }

    private function addText(ZipArchive $zip, string $path, string $content): void
    {
        $zip->addFromString($path, $content);
        if ($path !== 'PACKAGE_MANIFEST.md') {
            $this->manifest[] = '- `' . $path . '`';
        }
    }
}
