<?php
/**
 * gov.cabnet.app — EDXEIX submit payload validator.
 *
 * Validates the dry-run request generated by EdxeixSubmitConnector.
 * This class performs checks only. It does not call EDXEIX and does not write data.
 */

declare(strict_types=1);

namespace Bridge\Edxeix;

final class EdxeixSubmitPayloadValidator
{
    public const VERSION = 'v0.1.0-payload-validator-no-live-submit';

    /**
     * @param array<string,mixed> $request Dry-run connector request.
     * @param array<string,mixed>|null $capture Sanitized submit capture metadata.
     * @param array<string,mixed>|null $preflight Preflight gate result.
     * @param array<string,mixed> $options Reserved for future use.
     * @return array<string,mixed>
     */
    public function validate(array $request, ?array $capture = null, ?array $preflight = null, array $options = []): array
    {
        $capture = is_array($capture) ? $capture : [];
        $preflight = is_array($preflight) ? $preflight : [];
        $payload = is_array($request['payload_preview'] ?? null) ? $request['payload_preview'] : [];

        $blockers = [];
        $warnings = [];
        $facts = [];

        $method = strtoupper($this->str($request, 'method'));
        $actionHost = $this->str($request, 'action_host');
        $actionPath = $this->str($request, 'action_path');
        $facts['connector_version'] = $this->str($request, 'version');
        $facts['validator_version'] = self::VERSION;

        if (!in_array($method, ['POST', 'PUT', 'PATCH'], true)) {
            $blockers[] = 'invalid_or_missing_request_method';
        }
        if ($actionHost === '') {
            $blockers[] = 'missing_action_host';
        }
        if ($actionPath === '') {
            $blockers[] = 'missing_action_path';
        } elseif (!str_starts_with($actionPath, '/')) {
            $warnings[] = 'Action path does not start with /. Verify sanitized submit capture.';
        }
        if ($payload === []) {
            $blockers[] = 'empty_payload_preview';
        }

        $requiredFields = $this->splitFieldList($this->str($capture, 'required_field_names'));
        $selectFields = $this->splitFieldList($this->str($capture, 'select_field_names'));
        $coordinateFields = $this->splitFieldList($this->str($capture, 'coordinate_field_names'));
        $csrfFieldName = $this->firstNonEmpty([
            $this->str($capture, 'csrf_field_name'),
            $this->findLikelyCsrfField($payload),
            '_token',
        ]);

        $facts['required_field_count_from_capture'] = count($requiredFields);
        $facts['select_field_count_from_capture'] = count($selectFields);
        $facts['coordinate_field_count_from_capture'] = count($coordinateFields);
        $facts['payload_field_count'] = count($payload);
        $facts['csrf_field_name'] = $csrfFieldName;

        if ($requiredFields === []) {
            $blockers[] = 'missing_required_field_names_capture';
        }
        if ($selectFields === []) {
            $warnings[] = 'No select/dropdown field names recorded in sanitized capture.';
        }
        if ($coordinateFields === []) {
            $warnings[] = 'No coordinate/map field names recorded in sanitized capture.';
        }
        if ($csrfFieldName === '') {
            $blockers[] = 'missing_csrf_field_name';
        }

        $requiredPresent = [];
        $requiredMissing = [];
        foreach ($requiredFields as $fieldName) {
            if ($this->payloadValue($payload, $fieldName) !== '') {
                $requiredPresent[] = $fieldName;
            } else {
                $requiredMissing[] = $fieldName;
                $blockers[] = 'missing_required_payload_field_' . $this->slug($fieldName);
            }
        }

        foreach (['lessor', 'driver', 'vehicle', 'starting_point_id'] as $fieldName) {
            if ($this->payloadValue($payload, $fieldName) === '') {
                $blockers[] = 'missing_core_select_' . $fieldName;
            }
        }

        if ($this->payloadValue($payload, 'starting_point_id') !== '' && !$this->looksInteger($this->payloadValue($payload, 'starting_point_id'))) {
            $warnings[] = 'starting_point_id is present but does not look numeric.';
        }

        $coordinateCoverage = [];
        foreach ($coordinateFields as $fieldName) {
            $value = $this->payloadValue($payload, $fieldName);
            $coordinateCoverage[$fieldName] = $value !== '' ? 'present' : 'missing';
        }
        if ($coordinateFields !== [] && !in_array('present', $coordinateCoverage, true)) {
            $blockers[] = 'missing_coordinate_payload_fields';
        }
        foreach (['coordinates', 'locationCoordinates'] as $fieldName) {
            $value = $this->payloadValue($payload, $fieldName);
            if ($value !== '' && str_contains($value, '__OPERATOR_CONFIRMED_MAP_COORDINATES_REQUIRED__')) {
                $blockers[] = 'operator_confirmed_map_coordinates_missing';
            }
        }

        $sensitiveFindings = $this->findSensitivePayloadIssues($payload);
        foreach ($sensitiveFindings as $finding) {
            $blockers[] = 'sensitive_payload_issue_' . $this->slug($finding);
            $warnings[] = 'Sensitive payload issue: ' . $finding;
        }

        if (!empty($preflight['technical_blockers']) && is_array($preflight['technical_blockers'])) {
            foreach ($preflight['technical_blockers'] as $blocker) {
                $blocker = trim((string)$blocker);
                if ($blocker !== '') {
                    $blockers[] = 'preflight_' . $blocker;
                }
            }
        }

        foreach ((array)($request['blockers'] ?? []) as $blocker) {
            $blocker = trim((string)$blocker);
            if ($blocker !== '' && !str_contains($blocker, 'live_submit')) {
                $warnings[] = 'Connector blocker still present: ' . $blocker;
            }
        }

        $blockers[] = 'live_submit_disabled_by_design';
        $blockers[] = 'active_edxeix_session_bridge_not_implemented';
        $blockers[] = 'active_csrf_token_not_available_by_design';

        $blockers = array_values(array_unique(array_filter($blockers)));
        $warnings = array_values(array_unique(array_filter($warnings)));

        return [
            'ok' => true,
            'version' => self::VERSION,
            'dry_run_payload_valid' => count(array_diff($blockers, [
                'live_submit_disabled_by_design',
                'active_edxeix_session_bridge_not_implemented',
                'active_csrf_token_not_available_by_design',
                'operator_confirmed_map_coordinates_missing',
            ])) === 0,
            'live_submit_allowed' => false,
            'blockers' => $blockers,
            'warnings' => $warnings,
            'facts' => $facts,
            'required_present' => $requiredPresent,
            'required_missing' => $requiredMissing,
            'coordinate_coverage' => $coordinateCoverage,
            'safety_contract' => [
                'calls_edxeix' => false,
                'calls_bolt' => false,
                'calls_aade' => false,
                'writes_database' => false,
                'extracts_or_prints_cookie_values' => false,
                'extracts_or_prints_csrf_token_values' => false,
                'live_submit_default' => false,
            ],
        ];
    }

    /** @param array<string,mixed> $source */
    private function str(array $source, string $key): string
    {
        return trim((string)($source[$key] ?? ''));
    }

    /** @param array<int,string> $values */
    private function firstNonEmpty(array $values): string
    {
        foreach ($values as $value) {
            $value = trim($value);
            if ($value !== '') {
                return $value;
            }
        }
        return '';
    }

    /** @return array<int,string> */
    private function splitFieldList(string $value): array
    {
        $parts = preg_split('/[\r\n,;]+/', $value) ?: [];
        $out = [];
        foreach ($parts as $part) {
            $part = trim((string)$part);
            if ($part !== '') {
                $out[] = $part;
            }
        }
        return array_values(array_unique($out));
    }

    /** @param array<string,mixed> $payload */
    private function payloadValue(array $payload, string $fieldName): string
    {
        if (array_key_exists($fieldName, $payload)) {
            return trim((string)$payload[$fieldName]);
        }
        return '';
    }

    /** @param array<string,mixed> $payload */
    private function findLikelyCsrfField(array $payload): string
    {
        foreach (array_keys($payload) as $key) {
            $name = strtolower((string)$key);
            if ($name === '_token' || str_contains($name, 'csrf')) {
                return (string)$key;
            }
        }
        return '';
    }

    private function looksInteger(string $value): bool
    {
        return (bool)preg_match('/^\d+$/', $value);
    }

    /**
     * @param array<string,mixed> $payload
     * @return array<int,string>
     */
    private function findSensitivePayloadIssues(array $payload): array
    {
        $issues = [];
        foreach ($payload as $key => $value) {
            $keyText = strtolower((string)$key);
            $valueText = trim((string)$value);

            if (preg_match('/cookie|session|password|passwd|secret|credential|private_key/i', $keyText)) {
                $issues[] = 'sensitive_field_name_' . (string)$key;
            }

            if ($valueText === '') {
                continue;
            }

            // The dry-run connector is allowed to use explicit placeholders.
            if (str_starts_with($valueText, '__') && str_ends_with($valueText, '__')) {
                continue;
            }

            if (preg_match('/PHPSESSID|laravel_session|remember_web|XSRF-TOKEN|BEGIN\s+(RSA|OPENSSH|PRIVATE)\s+KEY/i', $valueText)) {
                $issues[] = 'sensitive_value_pattern_' . (string)$key;
            }
        }
        return array_values(array_unique($issues));
    }

    private function slug(string $value): string
    {
        $value = strtolower(trim($value));
        $value = preg_replace('/[^a-z0-9]+/', '_', $value) ?: $value;
        return trim($value, '_') ?: 'unknown';
    }
}
